
// @ts-ignore
import { jsPDF } from "jspdf";
// @ts-ignore
import autoTable from "jspdf-autotable";
import { HealthReport } from "../types";

export const generateReportPDF = (report: HealthReport) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // --- HEADER ---
  doc.setFillColor(13, 148, 136); // Teal-600
  doc.rect(0, 0, pageWidth, 24, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Health Sathi", 14, 16);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Powered Medical Assessment", pageWidth - 14, 16, { align: 'right' });

  let y = 40;

  // --- PATIENT INFO ---
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Patient: ${report.patientName}`, 14, y);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${new Date(report.timestamp).toLocaleString()}`, pageWidth - 14, y, { align: 'right' });
  y += 6;
  doc.setTextColor(100, 100, 100);
  doc.text(`Report ID: ${report.id}`, 14, y);
  doc.text(`Status: ${report.status}`, pageWidth - 14, y, { align: 'right' });
  
  y += 15;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 15;

  // --- SECTION 1: CLINICAL GUIDANCE ---
  if (report.aiAnalysis?.english_guidance) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(13, 148, 136); // Teal
    doc.text("Clinical Guidance", 14, y);
    y += 8;
    
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(11);
    
    const splitText = doc.splitTextToSize(report.aiAnalysis.english_guidance, pageWidth - 28);
    doc.text(splitText, 14, y);
    y += (splitText.length * 6) + 12;
  }

  // --- SECTION 2: VITALS & METRICS ---
  if (report.aiAnalysis?.extracted_values && Object.keys(report.aiAnalysis.extracted_values).length > 0) {
    // Check space
    if (y > 220) { doc.addPage(); y = 20; }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(13, 148, 136);
    doc.text("Extracted Vitals & Metrics", 14, y);
    y += 6;

    const vitalsData = Object.entries(report.aiAnalysis.extracted_values).map(([key, value]) => [key, value]);
    
    autoTable(doc, {
      startY: y,
      head: [['Metric', 'Value']],
      body: vitalsData,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229], textColor: 255 }, // Indigo
      styles: { fontSize: 10, cellPadding: 4 },
      columnStyles: { 0: { fontStyle: 'bold', width: 80 } },
      margin: { left: 14, right: 14 },
    });
    
    // @ts-ignore
    y = doc.lastAutoTable.finalY + 18;
  }

  // --- SECTION 3: MEDICATIONS ---
  if (report.aiAnalysis?.medication_details && report.aiAnalysis.medication_details.length > 0) {
     // Check space
     if (y > 220) { doc.addPage(); y = 20; }

     doc.setFont("helvetica", "bold");
     doc.setFontSize(14);
     doc.setTextColor(13, 148, 136);
     doc.text("Prescribed Medication Schedule", 14, y);
     y += 6;

     const medData = report.aiAnalysis.medication_details.map(m => [
       m.name,
       m.dosage,
       m.frequency,
       m.timing,
       m.instructions || '-'
     ]);

     autoTable(doc, {
       startY: y,
       head: [['Medicine', 'Dosage', 'Freq', 'Timing', 'Instructions']],
       body: medData,
       theme: 'striped',
       headStyles: { fillColor: [13, 148, 136] }, // Teal
       styles: { fontSize: 10, cellPadding: 3 },
       columnStyles: { 
         0: { fontStyle: 'bold' },
         4: { fontStyle: 'italic' }
       },
       margin: { left: 14, right: 14 },
     });

     // @ts-ignore
     y = doc.lastAutoTable.finalY + 18;
  }

  // --- SECTION 4: DOCTOR NOTES ---
  if (report.doctorNotes) {
    if (y > 230) { doc.addPage(); y = 20; }

    // Visual Box for Doctor Notes
    doc.setFillColor(238, 242, 255); // Indigo-50
    doc.setDrawColor(199, 210, 254); // Indigo-200
    // Estimate height
    const splitNote = doc.splitTextToSize(`"${report.doctorNotes}"`, pageWidth - 36);
    const boxHeight = (splitNote.length * 6) + 20;
    
    doc.roundedRect(14, y, pageWidth - 28, boxHeight, 3, 3, 'FD');
    
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(67, 56, 202); // Indigo-700
    doc.text("Doctor Verification Note", 20, y);
    
    y += 8;
    doc.setFont("helvetica", "italic");
    doc.setTextColor(55, 65, 81); // Slate-700
    doc.text(splitNote, 20, y);
    
    y += (splitNote.length * 6) + 15;
  }

  // --- FOOTER ---
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    const footerText = `Generated by Health Sathi AI • Page ${i} of ${pageCount}`;
    doc.text(footerText, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
  }

  doc.save(`HealthSathi_Assessment_${report.patientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
};
